service: Notifications

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  profile: ${opt:stage}
  timeout: 300
  memorySize: 128
  environment:
    TWITTER_CONSUMER_KEY: ${file(./serverless.env.yml):${opt:stage}.TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${file(./serverless.env.yml):${opt:stage}.TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${file(./serverless.env.yml):${opt:stage}.TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${file(./serverless.env.yml):${opt:stage}.TWITTER_ACCESS_TOKEN_SECRET}
functions:
  getTwitterData:
    handler: src/apis/getTwitter.getTwitterData
    events:
      - http:
          path: "getTwitterData"
          method: "get"
          cors: true
plugins:
  - serverless-offline